### ISSUE TITLE
script relion_localized_reconstruction_mask.py still uses Bsoft

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/localrec#18]
As Scipion is now required, would be good to change this script to create a mask directly in Scipion (or Xmipp?)

**Comment by delarosatrevin** [comment]
So, the mask should be a cubic volume (N x N x N pixels) all with ones? right?

**Comment by JuhaHuiskonen** [comment]
the script should create a spherical mask with a specified radius (and a soft edge) in the position of the the substructure in the particle reconstruction (defined as the end point of the sub-particle vector). Optionally symmetry will be imposed on the mask. The range of values in the final mask should be [0,1]. The size should be the size of the particle reconstruction (N) given by the user.

**Comment by delarosatrevin** [comment]
Ok, I was thinking in the dummy mask used for the non-substracting case

**Comment by JuhaHuiskonen** [comment]
luckily with scipion_split_particle_stacks function this dummy mask is not needed anymore

**Comment by delarosatrevin** [comment]
See PR #19 .
