### ISSUE TITLE
Problem about reproducing results of VP4 spike on Rotavirus

### ISSUE THREAD

**Issue by phonchi** [I2PC/localrec#23]
Dear developers:

Thanks for the great tools you have created.

Currently, I am trying to reproduce the second examples shown in the paper, but I met some difficulties.

The procedure I conducted is as follows:

1) Download the Rotavirus TLP image stack from the [website](http://grigoriefflab.janelia.org/rotavirustlp)
2) Transform TLP.par files into Star files using Scipion 
3) Identify one of the VP4 spikes using Chimera volume tracer on TLP_10.mrc map from the [website](http://grigoriefflab.janelia.org/rotavirustlp), and save the marker as cmm file
![image](https://user-images.githubusercontent.com/11373055/50133467-a9610a00-02c6-11e9-85df-81a670283b19.png)
4) Add origin to cmm file as follows:
```
<marker_set name="marker set 1">
<marker id="1" x="0" y="0" z="0" r="1" g="1" b="0" radius="95"/>
<marker id="2" x="-131.85" y="127.62" z="431.05" r="1" g="1" b="0" radius="95"/>
</marker_set>
```
5) Create a spherical mask with radius 310 pixels and set outside to 0 value to obtain the masked reconstruction 

![image](https://user-images.githubusercontent.com/11373055/50133733-c8ac6700-02c7-11e9-8fd9-5f62406f80f9.png)

6) Run the script (v1.2.0) with 
`scipion run relion_localized_reconstruction.py --prepare_particles --create_subparticles --extract_subparticles --reconstruct_subparticles --sym I2 --cmm spike.cmm --angpix 1.23 --particle_size 1000 --subparticle_size 190 --masked_map mask.vol --np 28 --j 28 --unique 1 --align_subparticles --output example particles.star  `

7) The reconstructed map from example_subtracted.star does not have clear spike
![image](https://user-images.githubusercontent.com/11373055/50134060-4c1a8800-02c9-11e9-958f-10fe04723048.png)
![image](https://user-images.githubusercontent.com/11373055/50133820-3193df00-02c8-11e9-98b6-448dd39f5548.png)

Any suggestions will be appreciated!

Thanks in advance!

**Comment by JuhaHuiskonen** [comment]
I am happy to help you to get this sorted with @serbanilca. First I would like you to check the input angles in particles.star to make sure the conversion from PAR to STAR has worked. Simply calculate a reconstruction using relion_reconstruct and particles.star. To speed thing up you can first bin the particles and/or use the low_pass option.  Do you get the correct map out?

**Comment by phonchi** [comment]
Thanks for the quick reply!

I conduct a quick test that inverts the contrast of TLP.mrc (To make particle white) and using the command `relion_reconstruct  --i particles.star --o  output_volume.vol --sym I2 --angpix 1.233 --maxres 5.000 --pad 2.000 --j 20 --ctf `.

I can not get the map as TLP_10.mrc, the spike is not clear in the map. Seems like the conversion is not correct from PAR to STAR. Do you have recommended way to convert PAR files to STAR files?

Thanks again for the help!

**Comment by JuhaHuiskonen** [comment]
First we converted the image stack:

relion_preprocess --o particles --operate_on TLP_stack_original.mrcs --invert_contrast --norm --bg_radius 490 --white_dust 5 --black_dust 5

New image stack is named particles.mrcs

Then we converted the PAR file to a STAR file, considering the following differences in conventions:

RELION          FREALIGN
rot             PHI
tilt            THETA
psi             PSI
originX         -Xoff
originY         -Yoff

First you should create a header:

relion_star_loopheader rlnVoltage rlnDefocusU rlnDefocusV rlnDefocusAngle rlnSphericalAberration rlnDetectorPixelSize rlnMagnification rlnAmplitudeContrast rlnImageName rlnOriginX rlnOriginY rlnAngleRot rlnAngleTilt rlnAnglePsi rlnRandomSubset > particles.star

Then the data lines (here using awk):

awk '{if ($1!="C") {printf "%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%06s%s\t%.6f\t%.6f\t%.6f\t%.6f\t%.6f\t%d\n", 300, $9, $10, $11, 2.0, 7.0, 56770, 0.10, $1, "@Particles/frames/particles.mrcs", $5*-1, $6*-1, $4, $3, $2, ($1%2)+1 }}' < TLP_10.par >> particles.star

Hope it works!

**Comment by phonchi** [comment]
Thanks for the suggestion!

Yes, it works well now by using the provided script. I can successfully reconstruct a map that is close to the map provided in original website. After following the procedure, I can obtain a map as follows:

![image](https://user-images.githubusercontent.com/11373055/50331344-488d3800-0539-11e9-978d-917ca3a76be9.png)

3D classification then conducted using the reconstructed map as reference as follows:

`mpirun -np 8 -bynode  which relion_refine_mpi --i example_subtracted.star --ref example_class001.mrc --tau2_fudge 4 --scale  --K 4 --strict_highres_exp 12.0 --iter 25 --norm --only_flip_phases --ctf  --o class3D  --norm  --sym C1  --firstiter_cc --skip_align  --flatten_solvent  --zero_mask  --ini_high 60.0 --angpix 1.23  --perturb 0 --j 8`

yields four classes as follows:

![image](https://user-images.githubusercontent.com/11373055/50331738-b71ec580-053a-11e9-8a4c-d23a36d453b8.png)

Class 1,3,4 shows only minor difference. So I use the Class 1,3,4 original subparticles (without subtraction) to do reconstruction using (about 19K particles):

`relion_reconstruct --i subparticles2.star --o subparticle2_3D.mrc --angpix 1.23 --j 28 --ctf`

The right one is after 3D classification, and the yellow one is before 3D classification:
![image](https://user-images.githubusercontent.com/11373055/50331998-b3d80980-053b-11e9-89d1-5a84697a6f75.png)

The difference seems not so clear compare with original paper.

Do you have any suggestions about the procedure or which part may not be accurate? 

Thanks again for the help!

**Comment by JuhaHuiskonen** [comment]
I am glad it worked for you. Next step is to split the data in two random halves (make sure that sub-particles that come from the same particle are assigned to the same random subset), calculate two half maps and then run post processing to estimate the resolution and Bfactor. You should see lower B-Factor after 3D classification as you have removed some sub-particles that were missing a spike.
